### ISSUE TITLE
Update the main README file

### ISSUE THREAD

**Issue by vaishnav-mk** [Data-Science-Community-SRM/Resourceify#32]
The main [README.md](https://github.com/Data-Science-Community-SRM/Resourceify/blob/master/README.md) file needs to be updated to display the recent additions like Web Dev and stuff

**Comment by TheShiveshNetwork** [comment]
Assign this to me

**Comment by vaishnav-mk** [comment]
@TheShiveshNetwork are you still working on it?

**Comment by TheShiveshNetwork** [comment]
@vaishnav-mk yeah, most probably I'll make a pull request in a few hours.
